services:
  - type: web
    name: multiagent-healthcare-demo
    env: python
    buildCommand: pip install -r requirements-cloud.txt
    startCommand: python web_demo/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 8080
    plan: free 